import {
  IHistoryDataCorrection,
  IMasterName,
} from './HistoryDataCorrectionModel';

export const HistoryData: IHistoryDataCorrection[] = [
  {
    id: 1,
    historyId: 'WM102_P20_Volume',
    timeStamp: '2023-12-01T16:29:00',
    value: 0,
    statusTags: 'Missing',
    trendFlags: 0,
    status: 0,
    trandFlagTag: '',
    correctedStatus: 0,
    correctionRule: 0,
    correctedValue: 148.25,
    color: 'purple',
    // "createdBy": 0,
    // "dateCreated": "2023-12-04T16:30:00",
    // "lastModifiedBy": 0,
    // "dateModified": 0,
    // "deletedBy": 0,
    // "dateDeleted": 0
  },
  {
    id: 2,
    historyId: 'KWH4_SR_Energy',
    timeStamp: '2023-12-05T16:15:00',
    value: 0,
    statusTags: 'Ok',
    trendFlags: 0,
    status: 0,
    trandFlagTag: '',
    correctedStatus: 0,
    correctionRule: 0,
    correctedValue: 158.25,
    color: 'lightblue',
    // "createdBy": 0,
    // "dateCreated": 0,
    // "lastModifiedBy": 0,
    // "dateModified": "2023-12-04T16:16:00",
    // "deletedBy": 0,
    // "dateDeleted": 0
  },
  {
    id: 3,
    historyId: 'WM102_N19_Volume',
    timeStamp: '2023-12-13T15:58:00',
    value: 0,
    statusTags: 'Missing',
    trendFlags: 0,
    status: 0,
    trandFlagTag: '',
    correctedStatus: 0,
    correctionRule: 0,
    correctedValue: 789.52,
    color: 'blue',
    // "createdBy": 0,
    // "dateCreated": 0,
    // "lastModifiedBy": 0,
    // "dateModified": "2023-12-01T16:27:00",
    // "deletedBy": 0,
    // "dateDeleted": 0
  },
  {
    id: 4,
    historyId: 'WM102_N19_Volume',
    timeStamp: '2023-12-13T15:58:00',
    value: 0,
    statusTags: 'Missing',
    trendFlags: 0,
    status: 0,
    trandFlagTag: '',
    correctedStatus: 0,
    correctionRule: 0,
    correctedValue: 789.52,
    color: 'tomato',
    // "createdBy": 0,
    // "dateCreated": 0,
    // "lastModifiedBy": 0,
    // "dateModified": "2023-12-01T16:27:00",
    // "deletedBy": 0,
    // "dateDeleted": 0
  },
  {
    id: 5,
    historyId: 'WM104_SR_Volume',
    timeStamp: '2023-12-15T15:45:00',
    value: 0,
    statusTags: 'missing',
    trendFlags: 0,
    status: 0,
    trandFlagTag: '',
    correctedStatus: 0,
    correctionRule: 0,
    correctedValue: 558.23,
    color: 'lightgreen',
    // "createdBy": 0,
    // "dateCreated": "2023-12-01T15:46:00",
    // "lastModifiedBy": 0,
    // "dateModified": 0,
    // "deletedBy": 0,
    // "dateDeleted": 0
  },
  {
    id: 6,
    historyId: 'WM102_P20_Volume',
    timeStamp: '2023-12-09T15:42:00',
    value: 0,
    statusTags: 'Missing',
    trendFlags: 0,
    status: 0,
    trandFlagTag: '',
    correctedStatus: 0,
    correctionRule: 0,
    correctedValue: 478.2,
    color: 'aqua',
    // "createdBy": 0,
    // "dateCreated": "2023-12-01T15:46:00",
    // "lastModifiedBy": 0,
    // "dateModified": 0,
    // "deletedBy": 0,
    // "dateDeleted": 0
  },
  {
    id: 7,
    historyId: 'WM102_P20_Volume',
    timeStamp: '2023-12-09T15:42:00',
    value: 0,
    statusTags: 'Missing',
    trendFlags: 0,
    status: 0,
    trandFlagTag: '',
    correctedStatus: 0,
    correctionRule: 0,
    correctedValue: 478.2,
    color: 'pink',
    // "createdBy": 0,
    // "dateCreated": "2023-12-01T15:46:00",
    // "lastModifiedBy": 0,
    // "dateModified": 0,
    // "deletedBy": 0,
    // "dateDeleted": 0
  },
  {
    id: 8,
    historyId: 'WM102_N19_Volume',
    timeStamp: '2023-12-25T15:34:00',
    value: 0,
    statusTags: 'Fine',
    trendFlags: 0,
    status: 0,
    trandFlagTag: '',
    correctedStatus: 0,
    correctionRule: 0,
    correctedValue: 258,
    color: 'red',
    // "createdBy": 0,
    // "dateCreated": "2023-12-01T15:35:00",
    // "lastModifiedBy": 0,
    // "dateModified": 0,
    // "deletedBy": 0,
    // "dateDeleted": 0
  },
  {
    id: 9,
    historyId: 'WM103_N35_Volume',
    timeStamp: '2023-12-01T15:18:00',
    value: 0,
    statusTags: 'ok',
    trendFlags: 0,
    status: 0,
    trandFlagTag: '',
    correctedStatus: 0,
    correctionRule: 0,
    correctedValue: 25,
    color: 'green',
    // "createdBy": 0,
    // "dateCreated": "2023-12-01T15:19:00",
    // "lastModifiedBy": 0,
    // "dateModified": 0,
    // "deletedBy": 0,
    // "dateDeleted": 0
  },
  {
    id: 10,
    historyId: 'WM103_N35_Volume',
    timeStamp: '2023-12-01T15:16:00',
    value: 0,
    statusTags: 'Missing',
    trendFlags: 0,
    status: 0,
    trandFlagTag: '',
    correctedStatus: 0,
    correctionRule: 0,
    correctedValue: 1789.23,
    color: 'yellow',
    //   "createdBy": 0,
    //   "dateCreated": "2023-12-01T15:17:00",
    //   "lastModifiedBy": 0,
    //   "dateModified": 0,
    //   "deletedBy": 0,
    //   "dateDeleted": 0
  },
];
export const MasterData: IMasterName[] = [
  {
    id: 1,
    historyId: '/Hawkesbury/WM101_N19_Volume',
    status: true,
  },
  {
    id: 2,
    historyId: '/Hawkesbury/KWH_1_Sub_10_Energy',
    status: true,
  },
  {
    id: 3,
    historyId: '/Bankstown/WM107_Building_6_Volume',
    status: true,
  },
  {
    id: 4,
    historyId: '/Nirimba/GM206_SR_Volume',
    status: true,
  },
  {
    id: 5,
    historyId: '/Kingswood/GM202_SR_Volume',
    status: true,
  },
  {
    id: 6,
    historyId: '/Bankstown/GM203_SR_Volume',
    status: true,
  },
  {
    id: 7,
    historyId: '/Campbelltown/WM109_23B1a_Volume',
    status: true,
  },
  {
    id: 8,
    historyId: '/Nirimba/KWH11_SR_Energy',
    status: true,
  },
  {
    id: 9,
    historyId: '/Kingswood/WM105_SR_Volume',
    status: true,
  },
  {
    id: 10,
    historyId: '/Campbelltown/WM108_23B8_Volume',
    status: true,
  },
];
